version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: caps-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: caps_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crime-gpt-network

  adminer:
    image: adminer:4-standalone
    container_name: caps-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - crime-gpt-network

networks:
  crime-gpt-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
